name: wifi_audio_stream
description: "A Flutter app for streaming live audio over WiFi."
publish_to: 'none'
version: 0.1.2+3

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  permission_handler: ^10.2.0
  network_info_plus: ^4.0.0
  device_info_plus: ^9.0.2
  web_socket_channel: ^2.2.0
  flutter_sound: 9.16.3
  fluttertoast: ^8.0.9
  share_plus: ^10.0.3
  path_provider: ^2.0.11
  wakelock_plus: ^1.2.8
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2
  bonsoir: ^5.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/www/
    - assets/introduction/step1.png
    - assets/introduction/step2.png
    - assets/introduction/step3.png
    - assets/introduction/step4.png
    - assets/introduction/step5.png

  # # Add split configuration
  # android:
  #   aot: true
  #   splitPerAbi: true  # Creates separate APKs for each architecture
